// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llsdhoxsdzpjjsxkeqom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxsc2Rob3hzZHpwampzeGtlcW9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MzE3NzEsImV4cCI6MjA2MjAwNzc3MX0.M-0fHoSKtC8ricTN0w8RlWEjESW028GdXc3nBAkLIQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);